using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MLMConquerorGlobalEdition.Domain.Entities.General;
using MLMConquerorGlobalEdition.Repository.Context;

namespace MLMConquerorGlobalEdition.Repository.Seeders;

public static class CountriesSeeder
{
    public static async Task SeedAsync(AppDbContext db, ILogger logger)
    {
        if (await db.Countries.AnyAsync())
        {
            logger.LogDebug("Countries already seeded. Skipping.");
            return;
        }

        var now = DateTime.UtcNow;
        var countries = new List<Country>
        {
            new Country { Iso2="AF", Iso3="AFG", NameEn="Afghanistan", NameNative="افغانستان", DefaultLanguageCode="fa", FlagEmoji="🇦🇫", PhoneCode="+93", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AL", Iso3="ALB", NameEn="Albania", NameNative="Shqipëria", DefaultLanguageCode="sq", FlagEmoji="🇦🇱", PhoneCode="+355", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DZ", Iso3="DZA", NameEn="Algeria", NameNative="الجزائر", DefaultLanguageCode="ar", FlagEmoji="🇩🇿", PhoneCode="+213", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AD", Iso3="AND", NameEn="Andorra", NameNative="Andorra", DefaultLanguageCode="ca", FlagEmoji="🇦🇩", PhoneCode="+376", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AO", Iso3="AGO", NameEn="Angola", NameNative="Angola", DefaultLanguageCode="pt", FlagEmoji="🇦🇴", PhoneCode="+244", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AG", Iso3="ATG", NameEn="Antigua and Barbuda", NameNative="Antigua and Barbuda", DefaultLanguageCode="en", FlagEmoji="🇦🇬", PhoneCode="+1-268", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AR", Iso3="ARG", NameEn="Argentina", NameNative="Argentina", DefaultLanguageCode="es", FlagEmoji="🇦🇷", PhoneCode="+54", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AM", Iso3="ARM", NameEn="Armenia", NameNative="Հայաստան", DefaultLanguageCode="hy", FlagEmoji="🇦🇲", PhoneCode="+374", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AU", Iso3="AUS", NameEn="Australia", NameNative="Australia", DefaultLanguageCode="en", FlagEmoji="🇦🇺", PhoneCode="+61", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AT", Iso3="AUT", NameEn="Austria", NameNative="Österreich", DefaultLanguageCode="de", FlagEmoji="🇦🇹", PhoneCode="+43", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AZ", Iso3="AZE", NameEn="Azerbaijan", NameNative="Azərbaycan", DefaultLanguageCode="az", FlagEmoji="🇦🇿", PhoneCode="+994", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BS", Iso3="BHS", NameEn="Bahamas", NameNative="Bahamas", DefaultLanguageCode="en", FlagEmoji="🇧🇸", PhoneCode="+1-242", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BH", Iso3="BHR", NameEn="Bahrain", NameNative="البحرين", DefaultLanguageCode="ar", FlagEmoji="🇧🇭", PhoneCode="+973", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BD", Iso3="BGD", NameEn="Bangladesh", NameNative="বাংলাদেশ", DefaultLanguageCode="bn", FlagEmoji="🇧🇩", PhoneCode="+880", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BB", Iso3="BRB", NameEn="Barbados", NameNative="Barbados", DefaultLanguageCode="en", FlagEmoji="🇧🇧", PhoneCode="+1-246", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BY", Iso3="BLR", NameEn="Belarus", NameNative="Беларусь", DefaultLanguageCode="be", FlagEmoji="🇧🇾", PhoneCode="+375", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BE", Iso3="BEL", NameEn="Belgium", NameNative="België", DefaultLanguageCode="nl", FlagEmoji="🇧🇪", PhoneCode="+32", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BZ", Iso3="BLZ", NameEn="Belize", NameNative="Belize", DefaultLanguageCode="en", FlagEmoji="🇧🇿", PhoneCode="+501", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BJ", Iso3="BEN", NameEn="Benin", NameNative="Bénin", DefaultLanguageCode="fr", FlagEmoji="🇧🇯", PhoneCode="+229", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BT", Iso3="BTN", NameEn="Bhutan", NameNative="འབྲུག", DefaultLanguageCode="dz", FlagEmoji="🇧🇹", PhoneCode="+975", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BO", Iso3="BOL", NameEn="Bolivia", NameNative="Bolivia", DefaultLanguageCode="es", FlagEmoji="🇧🇴", PhoneCode="+591", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BA", Iso3="BIH", NameEn="Bosnia and Herzegovina", NameNative="Bosna i Hercegovina", DefaultLanguageCode="bs", FlagEmoji="🇧🇦", PhoneCode="+387", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BW", Iso3="BWA", NameEn="Botswana", NameNative="Botswana", DefaultLanguageCode="en", FlagEmoji="🇧🇼", PhoneCode="+267", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BR", Iso3="BRA", NameEn="Brazil", NameNative="Brasil", DefaultLanguageCode="pt", FlagEmoji="🇧🇷", PhoneCode="+55", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BN", Iso3="BRN", NameEn="Brunei", NameNative="Brunei", DefaultLanguageCode="ms", FlagEmoji="🇧🇳", PhoneCode="+673", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BG", Iso3="BGR", NameEn="Bulgaria", NameNative="България", DefaultLanguageCode="bg", FlagEmoji="🇧🇬", PhoneCode="+359", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BF", Iso3="BFA", NameEn="Burkina Faso", NameNative="Burkina Faso", DefaultLanguageCode="fr", FlagEmoji="🇧🇫", PhoneCode="+226", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="BI", Iso3="BDI", NameEn="Burundi", NameNative="Burundi", DefaultLanguageCode="fr", FlagEmoji="🇧🇮", PhoneCode="+257", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CV", Iso3="CPV", NameEn="Cape Verde", NameNative="Cabo Verde", DefaultLanguageCode="pt", FlagEmoji="🇨🇻", PhoneCode="+238", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KH", Iso3="KHM", NameEn="Cambodia", NameNative="កម្ពុជា", DefaultLanguageCode="km", FlagEmoji="🇰🇭", PhoneCode="+855", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CM", Iso3="CMR", NameEn="Cameroon", NameNative="Cameroun", DefaultLanguageCode="fr", FlagEmoji="🇨🇲", PhoneCode="+237", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CA", Iso3="CAN", NameEn="Canada", NameNative="Canada", DefaultLanguageCode="en", FlagEmoji="🇨🇦", PhoneCode="+1", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CF", Iso3="CAF", NameEn="Central African Republic", NameNative="République centrafricaine", DefaultLanguageCode="fr", FlagEmoji="🇨🇫", PhoneCode="+236", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TD", Iso3="TCD", NameEn="Chad", NameNative="Tchad", DefaultLanguageCode="fr", FlagEmoji="🇹🇩", PhoneCode="+235", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CL", Iso3="CHL", NameEn="Chile", NameNative="Chile", DefaultLanguageCode="es", FlagEmoji="🇨🇱", PhoneCode="+56", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CN", Iso3="CHN", NameEn="China", NameNative="中国", DefaultLanguageCode="zh", FlagEmoji="🇨🇳", PhoneCode="+86", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CO", Iso3="COL", NameEn="Colombia", NameNative="Colombia", DefaultLanguageCode="es", FlagEmoji="🇨🇴", PhoneCode="+57", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KM", Iso3="COM", NameEn="Comoros", NameNative="جزر القمر", DefaultLanguageCode="ar", FlagEmoji="🇰🇲", PhoneCode="+269", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CG", Iso3="COG", NameEn="Congo", NameNative="Congo", DefaultLanguageCode="fr", FlagEmoji="🇨🇬", PhoneCode="+242", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CD", Iso3="COD", NameEn="Congo (DR)", NameNative="République démocratique du Congo", DefaultLanguageCode="fr", FlagEmoji="🇨🇩", PhoneCode="+243", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CR", Iso3="CRI", NameEn="Costa Rica", NameNative="Costa Rica", DefaultLanguageCode="es", FlagEmoji="🇨🇷", PhoneCode="+506", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="HR", Iso3="HRV", NameEn="Croatia", NameNative="Hrvatska", DefaultLanguageCode="hr", FlagEmoji="🇭🇷", PhoneCode="+385", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CU", Iso3="CUB", NameEn="Cuba", NameNative="Cuba", DefaultLanguageCode="es", FlagEmoji="🇨🇺", PhoneCode="+53", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CY", Iso3="CYP", NameEn="Cyprus", NameNative="Κύπρος", DefaultLanguageCode="el", FlagEmoji="🇨🇾", PhoneCode="+357", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CZ", Iso3="CZE", NameEn="Czech Republic", NameNative="Česká republika", DefaultLanguageCode="cs", FlagEmoji="🇨🇿", PhoneCode="+420", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DK", Iso3="DNK", NameEn="Denmark", NameNative="Danmark", DefaultLanguageCode="da", FlagEmoji="🇩🇰", PhoneCode="+45", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DJ", Iso3="DJI", NameEn="Djibouti", NameNative="Djibouti", DefaultLanguageCode="fr", FlagEmoji="🇩🇯", PhoneCode="+253", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DM", Iso3="DMA", NameEn="Dominica", NameNative="Dominica", DefaultLanguageCode="en", FlagEmoji="🇩🇲", PhoneCode="+1-767", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DO", Iso3="DOM", NameEn="Dominican Republic", NameNative="República Dominicana", DefaultLanguageCode="es", FlagEmoji="🇩🇴", PhoneCode="+1-809", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="EC", Iso3="ECU", NameEn="Ecuador", NameNative="Ecuador", DefaultLanguageCode="es", FlagEmoji="🇪🇨", PhoneCode="+593", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="EG", Iso3="EGY", NameEn="Egypt", NameNative="مصر", DefaultLanguageCode="ar", FlagEmoji="🇪🇬", PhoneCode="+20", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SV", Iso3="SLV", NameEn="El Salvador", NameNative="El Salvador", DefaultLanguageCode="es", FlagEmoji="🇸🇻", PhoneCode="+503", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GQ", Iso3="GNQ", NameEn="Equatorial Guinea", NameNative="Guinea Ecuatorial", DefaultLanguageCode="es", FlagEmoji="🇬🇶", PhoneCode="+240", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ER", Iso3="ERI", NameEn="Eritrea", NameNative="ኤርትራ", DefaultLanguageCode="ti", FlagEmoji="🇪🇷", PhoneCode="+291", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="EE", Iso3="EST", NameEn="Estonia", NameNative="Eesti", DefaultLanguageCode="et", FlagEmoji="🇪🇪", PhoneCode="+372", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SZ", Iso3="SWZ", NameEn="Eswatini", NameNative="Eswatini", DefaultLanguageCode="en", FlagEmoji="🇸🇿", PhoneCode="+268", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ET", Iso3="ETH", NameEn="Ethiopia", NameNative="ኢትዮጵያ", DefaultLanguageCode="am", FlagEmoji="🇪🇹", PhoneCode="+251", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="FJ", Iso3="FJI", NameEn="Fiji", NameNative="Fiji", DefaultLanguageCode="en", FlagEmoji="🇫🇯", PhoneCode="+679", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="FI", Iso3="FIN", NameEn="Finland", NameNative="Suomi", DefaultLanguageCode="fi", FlagEmoji="🇫🇮", PhoneCode="+358", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="FR", Iso3="FRA", NameEn="France", NameNative="France", DefaultLanguageCode="fr", FlagEmoji="🇫🇷", PhoneCode="+33", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GA", Iso3="GAB", NameEn="Gabon", NameNative="Gabon", DefaultLanguageCode="fr", FlagEmoji="🇬🇦", PhoneCode="+241", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GM", Iso3="GMB", NameEn="Gambia", NameNative="Gambia", DefaultLanguageCode="en", FlagEmoji="🇬🇲", PhoneCode="+220", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GE", Iso3="GEO", NameEn="Georgia", NameNative="საქართველო", DefaultLanguageCode="ka", FlagEmoji="🇬🇪", PhoneCode="+995", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="DE", Iso3="DEU", NameEn="Germany", NameNative="Deutschland", DefaultLanguageCode="de", FlagEmoji="🇩🇪", PhoneCode="+49", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GH", Iso3="GHA", NameEn="Ghana", NameNative="Ghana", DefaultLanguageCode="en", FlagEmoji="🇬🇭", PhoneCode="+233", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GR", Iso3="GRC", NameEn="Greece", NameNative="Ελλάδα", DefaultLanguageCode="el", FlagEmoji="🇬🇷", PhoneCode="+30", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GD", Iso3="GRD", NameEn="Grenada", NameNative="Grenada", DefaultLanguageCode="en", FlagEmoji="🇬🇩", PhoneCode="+1-473", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GT", Iso3="GTM", NameEn="Guatemala", NameNative="Guatemala", DefaultLanguageCode="es", FlagEmoji="🇬🇹", PhoneCode="+502", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GN", Iso3="GIN", NameEn="Guinea", NameNative="Guinée", DefaultLanguageCode="fr", FlagEmoji="🇬🇳", PhoneCode="+224", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GW", Iso3="GNB", NameEn="Guinea-Bissau", NameNative="Guiné-Bissau", DefaultLanguageCode="pt", FlagEmoji="🇬🇼", PhoneCode="+245", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GY", Iso3="GUY", NameEn="Guyana", NameNative="Guyana", DefaultLanguageCode="en", FlagEmoji="🇬🇾", PhoneCode="+592", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="HT", Iso3="HTI", NameEn="Haiti", NameNative="Haïti", DefaultLanguageCode="fr", FlagEmoji="🇭🇹", PhoneCode="+509", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="HN", Iso3="HND", NameEn="Honduras", NameNative="Honduras", DefaultLanguageCode="es", FlagEmoji="🇭🇳", PhoneCode="+504", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="HU", Iso3="HUN", NameEn="Hungary", NameNative="Magyarország", DefaultLanguageCode="hu", FlagEmoji="🇭🇺", PhoneCode="+36", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IS", Iso3="ISL", NameEn="Iceland", NameNative="Ísland", DefaultLanguageCode="is", FlagEmoji="🇮🇸", PhoneCode="+354", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IN", Iso3="IND", NameEn="India", NameNative="भारत", DefaultLanguageCode="hi", FlagEmoji="🇮🇳", PhoneCode="+91", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ID", Iso3="IDN", NameEn="Indonesia", NameNative="Indonesia", DefaultLanguageCode="id", FlagEmoji="🇮🇩", PhoneCode="+62", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IR", Iso3="IRN", NameEn="Iran", NameNative="ایران", DefaultLanguageCode="fa", FlagEmoji="🇮🇷", PhoneCode="+98", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IQ", Iso3="IRQ", NameEn="Iraq", NameNative="العراق", DefaultLanguageCode="ar", FlagEmoji="🇮🇶", PhoneCode="+964", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IE", Iso3="IRL", NameEn="Ireland", NameNative="Éire", DefaultLanguageCode="en", FlagEmoji="🇮🇪", PhoneCode="+353", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IL", Iso3="ISR", NameEn="Israel", NameNative="ישראל", DefaultLanguageCode="he", FlagEmoji="🇮🇱", PhoneCode="+972", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="IT", Iso3="ITA", NameEn="Italy", NameNative="Italia", DefaultLanguageCode="it", FlagEmoji="🇮🇹", PhoneCode="+39", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="JM", Iso3="JAM", NameEn="Jamaica", NameNative="Jamaica", DefaultLanguageCode="en", FlagEmoji="🇯🇲", PhoneCode="+1-876", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="JP", Iso3="JPN", NameEn="Japan", NameNative="日本", DefaultLanguageCode="ja", FlagEmoji="🇯🇵", PhoneCode="+81", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="JO", Iso3="JOR", NameEn="Jordan", NameNative="الأردن", DefaultLanguageCode="ar", FlagEmoji="🇯🇴", PhoneCode="+962", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KZ", Iso3="KAZ", NameEn="Kazakhstan", NameNative="Қазақстан", DefaultLanguageCode="kk", FlagEmoji="🇰🇿", PhoneCode="+7", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KE", Iso3="KEN", NameEn="Kenya", NameNative="Kenya", DefaultLanguageCode="sw", FlagEmoji="🇰🇪", PhoneCode="+254", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KI", Iso3="KIR", NameEn="Kiribati", NameNative="Kiribati", DefaultLanguageCode="en", FlagEmoji="🇰🇮", PhoneCode="+686", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KW", Iso3="KWT", NameEn="Kuwait", NameNative="الكويت", DefaultLanguageCode="ar", FlagEmoji="🇰🇼", PhoneCode="+965", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KG", Iso3="KGZ", NameEn="Kyrgyzstan", NameNative="Кыргызстан", DefaultLanguageCode="ky", FlagEmoji="🇰🇬", PhoneCode="+996", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LA", Iso3="LAO", NameEn="Laos", NameNative="ລາວ", DefaultLanguageCode="lo", FlagEmoji="🇱🇦", PhoneCode="+856", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LV", Iso3="LVA", NameEn="Latvia", NameNative="Latvija", DefaultLanguageCode="lv", FlagEmoji="🇱🇻", PhoneCode="+371", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LB", Iso3="LBN", NameEn="Lebanon", NameNative="لبنان", DefaultLanguageCode="ar", FlagEmoji="🇱🇧", PhoneCode="+961", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LS", Iso3="LSO", NameEn="Lesotho", NameNative="Lesotho", DefaultLanguageCode="st", FlagEmoji="🇱🇸", PhoneCode="+266", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LR", Iso3="LBR", NameEn="Liberia", NameNative="Liberia", DefaultLanguageCode="en", FlagEmoji="🇱🇷", PhoneCode="+231", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LY", Iso3="LBY", NameEn="Libya", NameNative="ليبيا", DefaultLanguageCode="ar", FlagEmoji="🇱🇾", PhoneCode="+218", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LI", Iso3="LIE", NameEn="Liechtenstein", NameNative="Liechtenstein", DefaultLanguageCode="de", FlagEmoji="🇱🇮", PhoneCode="+423", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LT", Iso3="LTU", NameEn="Lithuania", NameNative="Lietuva", DefaultLanguageCode="lt", FlagEmoji="🇱🇹", PhoneCode="+370", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LU", Iso3="LUX", NameEn="Luxembourg", NameNative="Luxembourg", DefaultLanguageCode="fr", FlagEmoji="🇱🇺", PhoneCode="+352", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MG", Iso3="MDG", NameEn="Madagascar", NameNative="Madagasikara", DefaultLanguageCode="mg", FlagEmoji="🇲🇬", PhoneCode="+261", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MW", Iso3="MWI", NameEn="Malawi", NameNative="Malawi", DefaultLanguageCode="ny", FlagEmoji="🇲🇼", PhoneCode="+265", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MY", Iso3="MYS", NameEn="Malaysia", NameNative="Malaysia", DefaultLanguageCode="ms", FlagEmoji="🇲🇾", PhoneCode="+60", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MV", Iso3="MDV", NameEn="Maldives", NameNative="ދިވެހިރާއްޖެ", DefaultLanguageCode="dv", FlagEmoji="🇲🇻", PhoneCode="+960", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ML", Iso3="MLI", NameEn="Mali", NameNative="Mali", DefaultLanguageCode="fr", FlagEmoji="🇲🇱", PhoneCode="+223", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MT", Iso3="MLT", NameEn="Malta", NameNative="Malta", DefaultLanguageCode="mt", FlagEmoji="🇲🇹", PhoneCode="+356", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MH", Iso3="MHL", NameEn="Marshall Islands", NameNative="Marshall Islands", DefaultLanguageCode="en", FlagEmoji="🇲🇭", PhoneCode="+692", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MR", Iso3="MRT", NameEn="Mauritania", NameNative="موريتانيا", DefaultLanguageCode="ar", FlagEmoji="🇲🇷", PhoneCode="+222", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MU", Iso3="MUS", NameEn="Mauritius", NameNative="Maurice", DefaultLanguageCode="fr", FlagEmoji="🇲🇺", PhoneCode="+230", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MX", Iso3="MEX", NameEn="Mexico", NameNative="México", DefaultLanguageCode="es", FlagEmoji="🇲🇽", PhoneCode="+52", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="FM", Iso3="FSM", NameEn="Micronesia", NameNative="Micronesia", DefaultLanguageCode="en", FlagEmoji="🇫🇲", PhoneCode="+691", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MD", Iso3="MDA", NameEn="Moldova", NameNative="Moldova", DefaultLanguageCode="ro", FlagEmoji="🇲🇩", PhoneCode="+373", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MC", Iso3="MCO", NameEn="Monaco", NameNative="Monaco", DefaultLanguageCode="fr", FlagEmoji="🇲🇨", PhoneCode="+377", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MN", Iso3="MNG", NameEn="Mongolia", NameNative="Монгол улс", DefaultLanguageCode="mn", FlagEmoji="🇲🇳", PhoneCode="+976", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ME", Iso3="MNE", NameEn="Montenegro", NameNative="Crna Gora", DefaultLanguageCode="sr", FlagEmoji="🇲🇪", PhoneCode="+382", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MA", Iso3="MAR", NameEn="Morocco", NameNative="المغرب", DefaultLanguageCode="ar", FlagEmoji="🇲🇦", PhoneCode="+212", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MZ", Iso3="MOZ", NameEn="Mozambique", NameNative="Moçambique", DefaultLanguageCode="pt", FlagEmoji="🇲🇿", PhoneCode="+258", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="MM", Iso3="MMR", NameEn="Myanmar", NameNative="မြန်မာ", DefaultLanguageCode="my", FlagEmoji="🇲🇲", PhoneCode="+95", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NA", Iso3="NAM", NameEn="Namibia", NameNative="Namibia", DefaultLanguageCode="en", FlagEmoji="🇳🇦", PhoneCode="+264", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NR", Iso3="NRU", NameEn="Nauru", NameNative="Nauru", DefaultLanguageCode="en", FlagEmoji="🇳🇷", PhoneCode="+674", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NP", Iso3="NPL", NameEn="Nepal", NameNative="नेपाल", DefaultLanguageCode="ne", FlagEmoji="🇳🇵", PhoneCode="+977", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NL", Iso3="NLD", NameEn="Netherlands", NameNative="Nederland", DefaultLanguageCode="nl", FlagEmoji="🇳🇱", PhoneCode="+31", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NZ", Iso3="NZL", NameEn="New Zealand", NameNative="New Zealand", DefaultLanguageCode="en", FlagEmoji="🇳🇿", PhoneCode="+64", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NI", Iso3="NIC", NameEn="Nicaragua", NameNative="Nicaragua", DefaultLanguageCode="es", FlagEmoji="🇳🇮", PhoneCode="+505", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NE", Iso3="NER", NameEn="Niger", NameNative="Niger", DefaultLanguageCode="fr", FlagEmoji="🇳🇪", PhoneCode="+227", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NG", Iso3="NGA", NameEn="Nigeria", NameNative="Nigeria", DefaultLanguageCode="en", FlagEmoji="🇳🇬", PhoneCode="+234", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="NO", Iso3="NOR", NameEn="Norway", NameNative="Norge", DefaultLanguageCode="no", FlagEmoji="🇳🇴", PhoneCode="+47", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="OM", Iso3="OMN", NameEn="Oman", NameNative="عُمان", DefaultLanguageCode="ar", FlagEmoji="🇴🇲", PhoneCode="+968", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PK", Iso3="PAK", NameEn="Pakistan", NameNative="پاکستان", DefaultLanguageCode="ur", FlagEmoji="🇵🇰", PhoneCode="+92", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PW", Iso3="PLW", NameEn="Palau", NameNative="Palau", DefaultLanguageCode="en", FlagEmoji="🇵🇼", PhoneCode="+680", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PA", Iso3="PAN", NameEn="Panama", NameNative="Panamá", DefaultLanguageCode="es", FlagEmoji="🇵🇦", PhoneCode="+507", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PG", Iso3="PNG", NameEn="Papua New Guinea", NameNative="Papua New Guinea", DefaultLanguageCode="en", FlagEmoji="🇵🇬", PhoneCode="+675", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PY", Iso3="PRY", NameEn="Paraguay", NameNative="Paraguay", DefaultLanguageCode="es", FlagEmoji="🇵🇾", PhoneCode="+595", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PE", Iso3="PER", NameEn="Peru", NameNative="Perú", DefaultLanguageCode="es", FlagEmoji="🇵🇪", PhoneCode="+51", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PH", Iso3="PHL", NameEn="Philippines", NameNative="Pilipinas", DefaultLanguageCode="fil", FlagEmoji="🇵🇭", PhoneCode="+63", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PL", Iso3="POL", NameEn="Poland", NameNative="Polska", DefaultLanguageCode="pl", FlagEmoji="🇵🇱", PhoneCode="+48", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="PT", Iso3="PRT", NameEn="Portugal", NameNative="Portugal", DefaultLanguageCode="pt", FlagEmoji="🇵🇹", PhoneCode="+351", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="QA", Iso3="QAT", NameEn="Qatar", NameNative="قطر", DefaultLanguageCode="ar", FlagEmoji="🇶🇦", PhoneCode="+974", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="RO", Iso3="ROU", NameEn="Romania", NameNative="România", DefaultLanguageCode="ro", FlagEmoji="🇷🇴", PhoneCode="+40", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="RU", Iso3="RUS", NameEn="Russia", NameNative="Россия", DefaultLanguageCode="ru", FlagEmoji="🇷🇺", PhoneCode="+7", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="RW", Iso3="RWA", NameEn="Rwanda", NameNative="Rwanda", DefaultLanguageCode="rw", FlagEmoji="🇷🇼", PhoneCode="+250", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="KN", Iso3="KNA", NameEn="Saint Kitts and Nevis", NameNative="Saint Kitts and Nevis", DefaultLanguageCode="en", FlagEmoji="🇰🇳", PhoneCode="+1-869", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LC", Iso3="LCA", NameEn="Saint Lucia", NameNative="Saint Lucia", DefaultLanguageCode="en", FlagEmoji="🇱🇨", PhoneCode="+1-758", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="VC", Iso3="VCT", NameEn="Saint Vincent and the Grenadines", NameNative="Saint Vincent and the Grenadines", DefaultLanguageCode="en", FlagEmoji="🇻🇨", PhoneCode="+1-784", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="WS", Iso3="WSM", NameEn="Samoa", NameNative="Samoa", DefaultLanguageCode="sm", FlagEmoji="🇼🇸", PhoneCode="+685", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SM", Iso3="SMR", NameEn="San Marino", NameNative="San Marino", DefaultLanguageCode="it", FlagEmoji="🇸🇲", PhoneCode="+378", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ST", Iso3="STP", NameEn="Sao Tome and Principe", NameNative="São Tomé e Príncipe", DefaultLanguageCode="pt", FlagEmoji="🇸🇹", PhoneCode="+239", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SA", Iso3="SAU", NameEn="Saudi Arabia", NameNative="المملكة العربية السعودية", DefaultLanguageCode="ar", FlagEmoji="🇸🇦", PhoneCode="+966", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SN", Iso3="SEN", NameEn="Senegal", NameNative="Sénégal", DefaultLanguageCode="fr", FlagEmoji="🇸🇳", PhoneCode="+221", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="RS", Iso3="SRB", NameEn="Serbia", NameNative="Србија", DefaultLanguageCode="sr", FlagEmoji="🇷🇸", PhoneCode="+381", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SC", Iso3="SYC", NameEn="Seychelles", NameNative="Seychelles", DefaultLanguageCode="fr", FlagEmoji="🇸🇨", PhoneCode="+248", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SL", Iso3="SLE", NameEn="Sierra Leone", NameNative="Sierra Leone", DefaultLanguageCode="en", FlagEmoji="🇸🇱", PhoneCode="+232", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SG", Iso3="SGP", NameEn="Singapore", NameNative="Singapore", DefaultLanguageCode="en", FlagEmoji="🇸🇬", PhoneCode="+65", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SK", Iso3="SVK", NameEn="Slovakia", NameNative="Slovensko", DefaultLanguageCode="sk", FlagEmoji="🇸🇰", PhoneCode="+421", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SI", Iso3="SVN", NameEn="Slovenia", NameNative="Slovenija", DefaultLanguageCode="sl", FlagEmoji="🇸🇮", PhoneCode="+386", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SB", Iso3="SLB", NameEn="Solomon Islands", NameNative="Solomon Islands", DefaultLanguageCode="en", FlagEmoji="🇸🇧", PhoneCode="+677", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SO", Iso3="SOM", NameEn="Somalia", NameNative="Soomaaliya", DefaultLanguageCode="so", FlagEmoji="🇸🇴", PhoneCode="+252", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ZA", Iso3="ZAF", NameEn="South Africa", NameNative="South Africa", DefaultLanguageCode="en", FlagEmoji="🇿🇦", PhoneCode="+27", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SS", Iso3="SSD", NameEn="South Sudan", NameNative="South Sudan", DefaultLanguageCode="en", FlagEmoji="🇸🇸", PhoneCode="+211", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ES", Iso3="ESP", NameEn="Spain", NameNative="España", DefaultLanguageCode="es", FlagEmoji="🇪🇸", PhoneCode="+34", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="LK", Iso3="LKA", NameEn="Sri Lanka", NameNative="ශ්‍රී ලංකාව", DefaultLanguageCode="si", FlagEmoji="🇱🇰", PhoneCode="+94", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SD", Iso3="SDN", NameEn="Sudan", NameNative="السودان", DefaultLanguageCode="ar", FlagEmoji="🇸🇩", PhoneCode="+249", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SR", Iso3="SUR", NameEn="Suriname", NameNative="Suriname", DefaultLanguageCode="nl", FlagEmoji="🇸🇷", PhoneCode="+597", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SE", Iso3="SWE", NameEn="Sweden", NameNative="Sverige", DefaultLanguageCode="sv", FlagEmoji="🇸🇪", PhoneCode="+46", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="CH", Iso3="CHE", NameEn="Switzerland", NameNative="Schweiz", DefaultLanguageCode="de", FlagEmoji="🇨🇭", PhoneCode="+41", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="SY", Iso3="SYR", NameEn="Syria", NameNative="سوريا", DefaultLanguageCode="ar", FlagEmoji="🇸🇾", PhoneCode="+963", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TW", Iso3="TWN", NameEn="Taiwan", NameNative="台灣", DefaultLanguageCode="zh", FlagEmoji="🇹🇼", PhoneCode="+886", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TJ", Iso3="TJK", NameEn="Tajikistan", NameNative="Тоҷикистон", DefaultLanguageCode="tg", FlagEmoji="🇹🇯", PhoneCode="+992", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TZ", Iso3="TZA", NameEn="Tanzania", NameNative="Tanzania", DefaultLanguageCode="sw", FlagEmoji="🇹🇿", PhoneCode="+255", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TH", Iso3="THA", NameEn="Thailand", NameNative="ประเทศไทย", DefaultLanguageCode="th", FlagEmoji="🇹🇭", PhoneCode="+66", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TL", Iso3="TLS", NameEn="Timor-Leste", NameNative="Timor-Leste", DefaultLanguageCode="pt", FlagEmoji="🇹🇱", PhoneCode="+670", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TG", Iso3="TGO", NameEn="Togo", NameNative="Togo", DefaultLanguageCode="fr", FlagEmoji="🇹🇬", PhoneCode="+228", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TO", Iso3="TON", NameEn="Tonga", NameNative="Tonga", DefaultLanguageCode="to", FlagEmoji="🇹🇴", PhoneCode="+676", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TT", Iso3="TTO", NameEn="Trinidad and Tobago", NameNative="Trinidad and Tobago", DefaultLanguageCode="en", FlagEmoji="🇹🇹", PhoneCode="+1-868", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TN", Iso3="TUN", NameEn="Tunisia", NameNative="تونس", DefaultLanguageCode="ar", FlagEmoji="🇹🇳", PhoneCode="+216", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TR", Iso3="TUR", NameEn="Turkey", NameNative="Türkiye", DefaultLanguageCode="tr", FlagEmoji="🇹🇷", PhoneCode="+90", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TM", Iso3="TKM", NameEn="Turkmenistan", NameNative="Türkmenistan", DefaultLanguageCode="tk", FlagEmoji="🇹🇲", PhoneCode="+993", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="TV", Iso3="TUV", NameEn="Tuvalu", NameNative="Tuvalu", DefaultLanguageCode="en", FlagEmoji="🇹🇻", PhoneCode="+688", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="UG", Iso3="UGA", NameEn="Uganda", NameNative="Uganda", DefaultLanguageCode="en", FlagEmoji="🇺🇬", PhoneCode="+256", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="UA", Iso3="UKR", NameEn="Ukraine", NameNative="Україна", DefaultLanguageCode="uk", FlagEmoji="🇺🇦", PhoneCode="+380", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="AE", Iso3="ARE", NameEn="United Arab Emirates", NameNative="الإمارات العربية المتحدة", DefaultLanguageCode="ar", FlagEmoji="🇦🇪", PhoneCode="+971", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="GB", Iso3="GBR", NameEn="United Kingdom", NameNative="United Kingdom", DefaultLanguageCode="en", FlagEmoji="🇬🇧", PhoneCode="+44", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="US", Iso3="USA", NameEn="United States", NameNative="United States", DefaultLanguageCode="en", FlagEmoji="🇺🇸", PhoneCode="+1", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="UY", Iso3="URY", NameEn="Uruguay", NameNative="Uruguay", DefaultLanguageCode="es", FlagEmoji="🇺🇾", PhoneCode="+598", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="UZ", Iso3="UZB", NameEn="Uzbekistan", NameNative="Oʻzbekiston", DefaultLanguageCode="uz", FlagEmoji="🇺🇿", PhoneCode="+998", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="VU", Iso3="VUT", NameEn="Vanuatu", NameNative="Vanuatu", DefaultLanguageCode="bi", FlagEmoji="🇻🇺", PhoneCode="+678", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="VE", Iso3="VEN", NameEn="Venezuela", NameNative="Venezuela", DefaultLanguageCode="es", FlagEmoji="🇻🇪", PhoneCode="+58", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="VN", Iso3="VNM", NameEn="Vietnam", NameNative="Việt Nam", DefaultLanguageCode="vi", FlagEmoji="🇻🇳", PhoneCode="+84", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="YE", Iso3="YEM", NameEn="Yemen", NameNative="اليمن", DefaultLanguageCode="ar", FlagEmoji="🇾🇪", PhoneCode="+967", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ZM", Iso3="ZMB", NameEn="Zambia", NameNative="Zambia", DefaultLanguageCode="en", FlagEmoji="🇿🇲", PhoneCode="+260", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
            new Country { Iso2="ZW", Iso3="ZWE", NameEn="Zimbabwe", NameNative="Zimbabwe", DefaultLanguageCode="en", FlagEmoji="🇿🇼", PhoneCode="+263", IsActive=false, SortOrder=0, CreatedBy="system", CreationDate=now },
        };

        await db.Countries.AddRangeAsync(countries);
        await db.SaveChangesAsync();
        logger.LogInformation("Seeded {Count} countries.", countries.Count);
    }
}
