using MLMConquerorGlobalEdition.Domain.Entities.General;
using MLMConquerorGlobalEdition.Domain.Enums;

namespace MLMConquerorGlobalEdition.Domain.Entities.Tokens;

public class TokenTransaction : AuditChangesLongKey
{
    public string MemberId { get; set; } = string.Empty;
    public int TokenTypeId { get; set; }
    public TokenTransactionType TransactionType { get; set; }
    public int Quantity { get; set; }
    public string? DistributedToMemberId { get; set; }
    public string? UsedByMemberId { get; set; }
    public DateTime? UsedAt { get; set; }
    public string? GeneratedPdfUrl { get; set; }

    /// <summary>
    /// Unique redeemable token code (a.k.a. TokenCode). Generated by <see cref="MLMConquerorGlobalEdition.SharedKernel.TokenCodeGenerator"/>.
    /// Rows where <see cref="ReferenceId"/> is non-null represent a single redeemable token *instance*;
    /// rows where it is null are pure ledger events (Distributed/Used).
    /// </summary>
    public string? ReferenceId { get; set; }
    public string? Notes { get; set; }

    // ───────────────────────────────────────────────────────────────────────
    // Token instance lifecycle (only meaningful when ReferenceId is non-null)
    // ───────────────────────────────────────────────────────────────────────

    /// <summary>
    /// MemberId of the original recipient when the token was first issued (admin grant or commission).
    /// Never changes once set.
    /// </summary>
    public string? OriginalOwnerMemberId { get; set; }

    /// <summary>
    /// MemberId of the previous owner if this instance has been transferred at least once.
    /// Null while the token is still owned by its original owner.
    /// </summary>
    public string? PreviousOwnerMemberId { get; set; }

    /// <summary>
    /// Lifecycle status of the redeemable instance.
    /// Defaults to <see cref="TokenInstanceStatus.Issued"/> for new rows.
    /// </summary>
    public TokenInstanceStatus Status { get; set; } = TokenInstanceStatus.Issued;

    /// <summary>
    /// Optional expiration date. When set and now &gt; ExpiresAt, the instance becomes ineligible to redeem.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// OrderId of the signup that consumed this token. Only set when Status = Used.
    /// </summary>
    public string? UsedOnOrderId { get; set; }
}
